
import { Project } from "../types";

function escapeHtml(s: string) {
  return (s || '').toString()
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Simple markdown-like parser to allow HTML pass-through for <details> tags
function renderNotesHtml(notes: string): string {
  if (!notes) return 'No notes added.';
  
  const parts = notes.split(/(<\/?details(?: open)?>|<\/?summary>)/g);
  
  return parts.map(part => {
    if (part.match(/<\/?details(?: open)?>|<\/?summary>/)) {
      return part; // Return tag as-is
    } else {
      return escapeHtml(part); // Escape text content
    }
  }).join('');
}

// Generate the Body HTML
function getCaseStudyBodyHtml(project: Project, includeAssets: boolean = true): string {
  const assetsHtml = (project.assets || []).map(a => {
    const displayUrl = a.url || a.dataURL;
    const isImage = a.type.startsWith('image');

    if (includeAssets && isImage && displayUrl) {
       return `
      <div class="asset-container" style="margin: 20px 0; padding: 15px; border: 1px solid #e5e7eb; border-radius: 8px; page-break-inside: avoid; background: #fff;">
        <div style="font-weight:700; margin-bottom: 10px; color: #111; font-size: 14px;">${escapeHtml(a.name)}</div>
        <img src="${displayUrl}" style="max-width:100%; max-height: 600px; height:auto; border-radius:6px; display: block; margin: 0 auto;" alt="${escapeHtml(a.name)}" crossorigin="anonymous" />
      </div>
    `;
    } else {
       return `
       <div style="margin: 10px 0; padding: 15px; background: #f9fafb; border-radius: 6px; color: #4b5563; border: 1px dashed #d1d5db; page-break-inside: avoid;">
          <div style="font-weight:600; font-size: 14px; color: #1f2937;">${escapeHtml(a.name)}</div>
          <div style="font-size: 12px; margin-top: 4px;">Type: ${a.type} ${a.size ? `(${Math.round(a.size/1024)}KB)` : ''}</div>
          ${a.url ? `<div style="margin-top:4px;"><a href="${a.url}" target="_blank" style="color: #2563eb; text-decoration: none; font-size: 12px;">Download / View Link</a></div>` : ''}
       </div>
       `;
    }
  }).join('');

  const stagesList = Object.entries(project.stages).map(([k, v]) => 
    `<li style="margin-bottom: 6px; list-style: none; color: #374151; font-size: 14px;">
      <span style="display: inline-block; width: 20px;">${v ? '✅' : '⚪️'}</span> ${escapeHtml(k)}
    </li>`
  ).join('');

  const notesHtml = renderNotesHtml(project.notes);

  return `
    <div class="case-study-wrapper" style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #1f2937; background: #ffffff; padding: 40px; max-width: 800px; margin: 0 auto;">
      <div style="text-align:right; font-size:10px; color:#9ca3af; margin-bottom:20px;">Generated by UXMate</div>
      
      <h1 style="border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 16px; color: #111827; font-size: 28px; font-weight: 800;">${escapeHtml(project.title)}</h1>
      
      <div style="color: #6b7280; font-size: 14px; margin-bottom: 32px;">
        <p style="margin-bottom: 4px; font-size: 16px; color: #4b5563;">${escapeHtml(project.desc)}</p>
        <p>Created: ${new Date(project.createdAt).toLocaleDateString()}</p>
      </div>

      <h2 style="margin-top: 32px; color: #111827; font-size: 20px; font-weight: 700; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">Project Notes & Research</h2>
      <div style="background: #f9fafb; padding: 16px; border-radius: 8px; border: 1px solid #e5e7eb; margin-top: 12px;">
        <div style="white-space: pre-wrap; font-family: inherit; margin: 0; font-size: 14px; color: #374151;">${notesHtml}</div>
      </div>

      <h2 style="margin-top: 32px; color: #111827; font-size: 20px; font-weight: 700; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">Process & Progress</h2>
      <ul style="padding-left: 0; margin-top: 12px;">${stagesList}</ul>

      <h2 style="margin-top: 32px; color: #111827; font-size: 20px; font-weight: 700; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">Assets & Visuals</h2>
      <div style="margin-top: 12px;">
        ${assetsHtml || '<p style="color: #6b7280; font-style: italic;">No assets attached.</p>'}
      </div>

      <hr style="margin-top: 48px; border: 0; border-top: 1px solid #e5e7eb;">
      <p style="text-align: center; color: #9ca3af; font-size: 12px; margin-top: 16px;">Exported from UXMate Project Coach</p>
    </div>
  `;
}

// --- IMAGE INLINING UTILITIES ---

async function urlToDataUri(url: string): Promise<string> {
  try {
    const response = await fetch(url, { mode: 'cors', cache: 'no-cache' });
    if (!response.ok) throw new Error(`Failed to fetch ${url}`);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn('Export: Could not inline image, keeping original URL.', url);
    return url;
  }
}

async function inlineImagesInContainer(container: HTMLElement) {
  const images = Array.from(container.querySelectorAll('img'));
  const promises = images.map(async (img) => {
    // If already data URI, skip
    if (img.src.startsWith('data:')) return;
    // If blob URL (local preview), fetch and inline
    // If remote URL, fetch and inline (handles CORS if server allows)
    const newDataUri = await urlToDataUri(img.src);
    if (newDataUri !== img.src) {
      img.src = newDataUri;
    }
  });
  await Promise.all(promises);
}

// --- MAIN EXPORT FUNCTIONS ---

export function generateFullHtml(project: Project, includeAssets: boolean = true): string {
  const bodyContent = getCaseStudyBodyHtml(project, includeAssets);
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(project.title)} — Case Study</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1f2937; margin: 0; padding: 0; background: #f3f4f6; }
    img { display: block; margin: 0 auto; }
    details { margin: 10px 0; border: 1px solid #e5e7eb; border-radius: 6px; padding: 8px; background: #fff; }
    summary { font-weight: 600; cursor: pointer; color: #2563eb; outline: none; }
    details[open] summary { margin-bottom: 8px; border-bottom: 1px dashed #e5e7eb; padding-bottom: 4px; }
    @media print {
      body { background: white; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .case-study-wrapper { padding: 0 !important; margin: 0 !important; max-width: 100% !important; }
    }
  </style>
</head>
<body>
  ${bodyContent}
</body>
</html>`;
}

/**
 * Generates a printable HTML string with inlined images and current page styles.
 */
export async function generatePrintableDocument(project: Project, includeAssets: boolean): Promise<string> {
  // 1. Create a temporary container to process the HTML
  const container = document.createElement('div');
  container.innerHTML = getCaseStudyBodyHtml(project, includeAssets);
  
  // 2. Inline images for robustness in new window / PDF
  if (includeAssets) {
    await inlineImagesInContainer(container);
  }

  // 3. Collect Styles from current document to ensure consistent look (Tailwind etc)
  let styleTags = '';
  document.querySelectorAll('style').forEach(tag => {
    styleTags += tag.outerHTML;
  });
  
  // 4. Add Tailwind CDN explicitly if not found (fallback)
  if (!styleTags.includes('tailwindcss')) {
    styleTags += `<script src="https://cdn.tailwindcss.com"></script>`;
  }

  const finalHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${escapeHtml(project.title)}</title>
      ${styleTags}
      <style>
        @media print {
          @page { margin: 15mm; size: A4; }
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; background: white !important; }
          /* Hide typical web UI elements if they sneak in */
          button, input { display: none !important; }
        }
        body { background-color: #f3f4f6; margin: 0; padding: 20px; font-family: 'Inter', sans-serif; }
      </style>
    </head>
    <body>
      ${container.innerHTML}
      <script>
        // Auto-print when loaded
        window.onload = () => {
          setTimeout(() => {
            window.print();
            // Optional: window.close(); // Don't auto-close so user can see result if print fails
          }, 500);
        };
      </script>
    </body>
    </html>
  `;
  
  return finalHtml;
}

export function downloadAsHtmlFile(htmlContent: string, filename: string) {
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Main Export Function for "PDF / Print"
 * Tries to open a new window and print. 
 * If blocked, falls back to downloading the HTML file.
 */
export async function exportToPrintable(project: Project, includeAssets: boolean = true): Promise<{ success: boolean; method: 'print' | 'download' }> {
  const filename = `${(project.title || 'case-study').replace(/[^a-z0-9]/gi, '_')}.html`;
  const htmlContent = await generatePrintableDocument(project, includeAssets);

  // Attempt to open new window
  const printWindow = window.open('', '_blank');
  
  if (printWindow) {
    try {
      printWindow.document.open();
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      return { success: true, method: 'print' };
    } catch (e) {
      console.error('Export: Failed to write to print window', e);
      printWindow.close();
      downloadAsHtmlFile(htmlContent, filename);
      return { success: false, method: 'download' };
    }
  } else {
    // Popup blocked
    console.warn('Export: Popup blocked. Falling back to download.');
    downloadAsHtmlFile(htmlContent, filename);
    return { success: true, method: 'download' };
  }
}

// Alias for the simple HTML download
export function downloadCaseStudy(project: Project, includeAssets: boolean = true) {
  const htmlContent = generateFullHtml(project, includeAssets);
  const filename = `${(project.title || 'case-study').replace(/[^a-z0-9]/gi, '_')}.html`;
  downloadAsHtmlFile(htmlContent, filename);
}
